// Package openapi Code generated by swaggo/swag. DO NOT EDIT
package openapi

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/folders": {
            "get": {
                "description": "Returns all folders for a workspace, ordered by position.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "List folders",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_folder.Folder"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new folder in the workspace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Create folder",
                "parameters": [
                    {
                        "description": "Folder input",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_folder.CreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_folder.Folder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "409": {
                        "description": "Folder name already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/folders/{id}": {
            "get": {
                "description": "Returns a single folder by ID within a workspace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Get folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_folder.Folder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-deletes a folder. Links in the folder become unfiled.",
                "tags": [
                    "folders"
                ],
                "summary": "Delete folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates a folder. Only provided fields are changed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "folders"
                ],
                "summary": "Update folder",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Folder ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_folder.UpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_folder.Folder"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "409": {
                        "description": "Folder name already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/links": {
            "get": {
                "description": "Returns a paginated list of links for a workspace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "links"
                ],
                "summary": "List links",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated list of links",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new short link in the workspace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "links"
                ],
                "summary": "Create link",
                "parameters": [
                    {
                        "description": "Link input",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_link.CreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_link.Link"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "409": {
                        "description": "Short code already in use",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/links/{id}": {
            "get": {
                "description": "Returns a single link by ID within a workspace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "links"
                ],
                "summary": "Get link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Link ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_link.Link"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-deletes a link. The link is not permanently removed.",
                "tags": [
                    "links"
                ],
                "summary": "Delete link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Link ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates a link. Only provided fields are changed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "links"
                ],
                "summary": "Update link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Link ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_link.UpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_link.Link"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/links/{id}/tags": {
            "get": {
                "description": "Returns all tags associated with a link.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List tags for link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Link ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_tag.Tag"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Associates a tag with a link. Idempotent — no error if already associated.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Add tag to link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Link ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tag to associate",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_tag.AddToLinkInput"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/links/{id}/tags/{tag_id}": {
            "delete": {
                "description": "Removes a tag association from a link.",
                "tags": [
                    "tags"
                ],
                "summary": "Remove tag from link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Link ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/tags": {
            "get": {
                "description": "Returns all tags for a workspace, ordered by name.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "List tags",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/internal_tag.Tag"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new tag in the workspace.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Create tag",
                "parameters": [
                    {
                        "description": "Tag input",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_tag.CreateInput"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internal_tag.Tag"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "409": {
                        "description": "Tag name already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            }
        },
        "/api/v1/tags/{id}": {
            "get": {
                "description": "Returns a single tag by ID within a workspace.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Get tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_tag.Tag"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "delete": {
                "description": "Soft-deletes a tag. Removes it from all links.",
                "tags": [
                    "tags"
                ],
                "summary": "Delete tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates a tag. Only provided fields are changed.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tags"
                ],
                "summary": "Update tag",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Tag ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Workspace ID",
                        "name": "workspace_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Fields to update",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_tag.UpdateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_tag.Tag"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "409": {
                        "description": "Tag name already exists",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "422": {
                        "description": "Validation failed",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            }
        },
        "/{code}": {
            "get": {
                "description": "Resolves a short code and redirects to the destination URL.",
                "tags": [
                    "redirect"
                ],
                "summary": "Redirect short link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Short code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "302": {
                        "description": "Redirect to destination"
                    },
                    "404": {
                        "description": "Link not found, inactive, or expired",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_execrc_betteroute_internal_errs.Error": {
            "type": "object",
            "properties": {
                "detail": {
                    "type": "string"
                },
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_execrc_betteroute_internal_errs.FieldError"
                    }
                },
                "instance": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "retry_after": {
                    "type": "integer"
                },
                "status": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "github_com_execrc_betteroute_internal_errs.FieldError": {
            "type": "object",
            "properties": {
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_folder.CreateInput": {
            "type": "object",
            "required": [
                "name",
                "workspace_id"
            ],
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "internal_folder.Folder": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "position": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "internal_folder.UpdateInput": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 100,
                    "minLength": 1
                },
                "position": {
                    "type": "integer"
                }
            }
        },
        "internal_link.CreateInput": {
            "type": "object",
            "required": [
                "dest_url",
                "workspace_id"
            ],
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "dest_url": {
                    "type": "string",
                    "maxLength": 2048
                },
                "expiration_url": {
                    "type": "string",
                    "maxLength": 2048
                },
                "expires_at": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "max_clicks": {
                    "description": "Click limits",
                    "type": "integer"
                },
                "notes": {
                    "description": "Internal",
                    "type": "string",
                    "maxLength": 5000
                },
                "og_description": {
                    "type": "string",
                    "maxLength": 500
                },
                "og_image": {
                    "type": "string",
                    "maxLength": 2048
                },
                "og_title": {
                    "description": "OG metadata overrides",
                    "type": "string",
                    "maxLength": 200
                },
                "short_code": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "starts_at": {
                    "description": "Scheduling",
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200
                },
                "utm_campaign": {
                    "type": "string",
                    "maxLength": 200
                },
                "utm_content": {
                    "type": "string",
                    "maxLength": 200
                },
                "utm_medium": {
                    "type": "string",
                    "maxLength": 200
                },
                "utm_source": {
                    "description": "UTM parameters",
                    "type": "string",
                    "maxLength": 200
                },
                "utm_term": {
                    "type": "string",
                    "maxLength": 200
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "internal_link.Link": {
            "type": "object",
            "properties": {
                "click_count": {
                    "description": "Analytics (denormalized)",
                    "type": "integer"
                },
                "created_at": {
                    "description": "Timestamps",
                    "type": "string"
                },
                "created_via": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "dest_url": {
                    "type": "string"
                },
                "expiration_url": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "description": "Status \u0026 Scheduling",
                    "type": "boolean"
                },
                "last_clicked_at": {
                    "type": "string"
                },
                "max_clicks": {
                    "description": "Click limits",
                    "type": "integer"
                },
                "notes": {
                    "description": "Internal",
                    "type": "string"
                },
                "og_description": {
                    "type": "string"
                },
                "og_image": {
                    "type": "string"
                },
                "og_title": {
                    "description": "OG metadata overrides",
                    "type": "string"
                },
                "short_code": {
                    "type": "string"
                },
                "short_url": {
                    "type": "string"
                },
                "starts_at": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "unique_click_count": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                },
                "utm_campaign": {
                    "type": "string"
                },
                "utm_content": {
                    "type": "string"
                },
                "utm_medium": {
                    "type": "string"
                },
                "utm_source": {
                    "description": "UTM parameters",
                    "type": "string"
                },
                "utm_term": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "internal_link.UpdateInput": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "maxLength": 500
                },
                "dest_url": {
                    "type": "string",
                    "maxLength": 2048
                },
                "expiration_url": {
                    "type": "string",
                    "maxLength": 2048
                },
                "expires_at": {
                    "type": "string"
                },
                "folder_id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "max_clicks": {
                    "description": "Click limits",
                    "type": "integer"
                },
                "notes": {
                    "description": "Internal",
                    "type": "string",
                    "maxLength": 5000
                },
                "og_description": {
                    "type": "string",
                    "maxLength": 500
                },
                "og_image": {
                    "type": "string",
                    "maxLength": 2048
                },
                "og_title": {
                    "description": "OG metadata overrides",
                    "type": "string",
                    "maxLength": 200
                },
                "starts_at": {
                    "description": "Scheduling",
                    "type": "string"
                },
                "title": {
                    "type": "string",
                    "maxLength": 200
                },
                "utm_campaign": {
                    "type": "string",
                    "maxLength": 200
                },
                "utm_content": {
                    "type": "string",
                    "maxLength": 200
                },
                "utm_medium": {
                    "type": "string",
                    "maxLength": 200
                },
                "utm_source": {
                    "description": "UTM parameters",
                    "type": "string",
                    "maxLength": 200
                },
                "utm_term": {
                    "type": "string",
                    "maxLength": 200
                }
            }
        },
        "internal_tag.AddToLinkInput": {
            "type": "object",
            "required": [
                "tag_id"
            ],
            "properties": {
                "tag_id": {
                    "type": "string"
                }
            }
        },
        "internal_tag.CreateInput": {
            "type": "object",
            "required": [
                "name",
                "workspace_id"
            ],
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "internal_tag.Tag": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "workspace_id": {
                    "type": "string"
                }
            }
        },
        "internal_tag.UpdateInput": {
            "type": "object",
            "properties": {
                "color": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Betteroute API",
	Description:      "Open-source link management platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
