// Package openapi provides the embedded OpenAPI specification generated by swag.
package openapi

import _ "embed"

// Spec contains the generated OpenAPI specification.
//
//go:embed swagger.json
var Spec []byte
