// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
	"time"
)

const countAPIKeysByWorkspace = `-- name: CountAPIKeysByWorkspace :one
SELECT COUNT(*) FROM api_keys
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountAPIKeysByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeysByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findAPIKeyByHash = `-- name: FindAPIKeyByHash :one
SELECT id, workspace_id, created_by, permission, scopes, expires_at
FROM api_keys
WHERE key_hash = $1 AND deleted_at IS NULL
`

type FindAPIKeyByHashRow struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	CreatedBy   *string    `json:"created_by"`
	Permission  string     `json:"permission"`
	Scopes      []string   `json:"scopes"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

// Auth hot path: resolve key hash → workspace + scoping + creator.
// Index-only scan via idx_api_keys_hash.
func (q *Queries) FindAPIKeyByHash(ctx context.Context, keyHash string) (FindAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByHash, keyHash)
	var i FindAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Permission,
		&i.Scopes,
		&i.ExpiresAt,
	)
	return i, err
}

const findAPIKeyByID = `-- name: FindAPIKeyByID :one
SELECT id, workspace_id, created_by, name, key_hash, key_prefix, permission, scopes, expires_at, last_used_at, deleted_at, created_at, updated_at FROM api_keys
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type FindAPIKeyByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindAPIKeyByID(ctx context.Context, arg FindAPIKeyByIDParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByID, arg.ID, arg.WorkspaceID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Permission,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (
    id, workspace_id, created_by, name, key_hash, key_prefix, permission, scopes, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, workspace_id, created_by, name, key_hash, key_prefix, permission, scopes, expires_at, last_used_at, deleted_at, created_at, updated_at
`

type InsertAPIKeyParams struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	CreatedBy   *string    `json:"created_by"`
	Name        string     `json:"name"`
	KeyHash     string     `json:"key_hash"`
	KeyPrefix   string     `json:"key_prefix"`
	Permission  string     `json:"permission"`
	Scopes      []string   `json:"scopes"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Permission,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Permission,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAPIKeysByWorkspace = `-- name: ListAPIKeysByWorkspace :many
SELECT id, workspace_id, created_by, name, key_hash, key_prefix, permission, scopes, expires_at, last_used_at, deleted_at, created_at, updated_at FROM api_keys
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeysByWorkspace(ctx context.Context, workspaceID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.Name,
			&i.KeyHash,
			&i.KeyPrefix,
			&i.Permission,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAPIKey = `-- name: SoftDeleteAPIKey :execrows
UPDATE api_keys SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SoftDeleteAPIKeyParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteAPIKey(ctx context.Context, arg SoftDeleteAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAPIKey, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
