// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth.sql

package sqlc

import (
	"context"
	"time"
)

const countRecentVerificationTokens = `-- name: CountRecentVerificationTokens :one
SELECT COUNT(*)::int FROM verification_tokens
WHERE lower(email) = $1
  AND type = $2
  AND created_at > NOW() - INTERVAL '1 hour'
`

type CountRecentVerificationTokensParams struct {
	Email string `json:"email"`
	Type  string `json:"type"`
}

// Rate limit: count tokens issued for this email+type in the last hour.
// Used to prevent abuse of password reset and verification email endpoints.
func (q *Queries) CountRecentVerificationTokens(ctx context.Context, arg CountRecentVerificationTokensParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentVerificationTokens, arg.Email, arg.Type)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const findAccountByProvider = `-- name: FindAccountByProvider :one
SELECT id, user_id, provider, provider_account_id, created_at, updated_at FROM accounts
WHERE provider = $1 AND provider_account_id = $2
`

type FindAccountByProviderParams struct {
	Provider          string `json:"provider"`
	ProviderAccountID string `json:"provider_account_id"`
}

func (q *Queries) FindAccountByProvider(ctx context.Context, arg FindAccountByProviderParams) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByProvider, arg.Provider, arg.ProviderAccountID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findAccountsByUser = `-- name: FindAccountsByUser :many
SELECT id, user_id, provider, provider_account_id, created_at, updated_at FROM accounts
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) FindAccountsByUser(ctx context.Context, userID string) ([]Account, error) {
	rows, err := q.db.Query(ctx, findAccountsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findSessionByTokenHash = `-- name: FindSessionByTokenHash :one
SELECT
    s.id         AS session_id,
    s.expires_at AS session_expires_at,
    s.created_at AS session_created_at,
    u.id,
    u.name,
    u.email,
    u.email_verified_at,
    u.avatar_url,
    u.status,
    u.onboarded_at,
    u.timezone,
    u.last_login_at,
    u.created_at,
    u.updated_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.expires_at > NOW()
  AND u.deleted_at IS NULL
`

type FindSessionByTokenHashRow struct {
	SessionID        string     `json:"session_id"`
	SessionExpiresAt time.Time  `json:"session_expires_at"`
	SessionCreatedAt time.Time  `json:"session_created_at"`
	ID               string     `json:"id"`
	Name             string     `json:"name"`
	Email            string     `json:"email"`
	EmailVerifiedAt  *time.Time `json:"email_verified_at"`
	AvatarUrl        *string    `json:"avatar_url"`
	Status           string     `json:"status"`
	OnboardedAt      *time.Time `json:"onboarded_at"`
	Timezone         string     `json:"timezone"`
	LastLoginAt      *time.Time `json:"last_login_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

// Auth middleware hot path: validates session and loads user in one round-trip.
// The covering index on token_hash INCLUDE (user_id, expires_at) satisfies the
// session lookup without a heap fetch; the JOIN then loads the user row.
func (q *Queries) FindSessionByTokenHash(ctx context.Context, tokenHash string) (FindSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, findSessionByTokenHash, tokenHash)
	var i FindSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.SessionExpiresAt,
		&i.SessionCreatedAt,
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.AvatarUrl,
		&i.Status,
		&i.OnboardedAt,
		&i.Timezone,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, email, email_verified_at, avatar_url, status, onboarded_at, last_login_at, timezone, deleted_at, created_at, updated_at FROM users
WHERE lower(email) = $1 AND deleted_at IS NULL
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.AvatarUrl,
		&i.Status,
		&i.OnboardedAt,
		&i.LastLoginAt,
		&i.Timezone,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, name, email, email_verified_at, avatar_url, status, onboarded_at, last_login_at, timezone, deleted_at, created_at, updated_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.AvatarUrl,
		&i.Status,
		&i.OnboardedAt,
		&i.LastLoginAt,
		&i.Timezone,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findVerificationTokenByHash = `-- name: FindVerificationTokenByHash :one
SELECT id, user_id, email, token_hash, type, expires_at, used_at, created_at FROM verification_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) FindVerificationTokenByHash(ctx context.Context, tokenHash string) (VerificationToken, error) {
	row := q.db.QueryRow(ctx, findVerificationTokenByHash, tokenHash)
	var i VerificationToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.TokenHash,
		&i.Type,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :one

INSERT INTO accounts (id, user_id, provider, provider_account_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, NOW(), NOW())
RETURNING id, user_id, provider, provider_account_id, created_at, updated_at
`

type InsertAccountParams struct {
	ID                string `json:"id"`
	UserID            string `json:"user_id"`
	Provider          string `json:"provider"`
	ProviderAccountID string `json:"provider_account_id"`
}

// Accounts
func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, insertAccount,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderAccountID,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one

INSERT INTO sessions (id, user_id, token_hash, expires_at, ip_address, user_agent, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
RETURNING id, user_id, token_hash, expires_at, ip_address, user_agent, created_at, updated_at
`

type InsertSessionParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
}

// Sessions
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one

INSERT INTO users (id, name, email, avatar_url)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, email_verified_at, avatar_url, status, onboarded_at, last_login_at, timezone, deleted_at, created_at, updated_at
`

type InsertUserParams struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	AvatarUrl *string `json:"avatar_url"`
}

// Users
func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, insertUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.AvatarUrl,
		&i.Status,
		&i.OnboardedAt,
		&i.LastLoginAt,
		&i.Timezone,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertVerificationToken = `-- name: InsertVerificationToken :exec

INSERT INTO verification_tokens (id, user_id, email, token_hash, type, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW())
`

type InsertVerificationTokenParams struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Email     string    `json:"email"`
	TokenHash string    `json:"token_hash"`
	Type      string    `json:"type"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Verification tokens
func (q *Queries) InsertVerificationToken(ctx context.Context, arg InsertVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, insertVerificationToken,
		arg.ID,
		arg.UserID,
		arg.Email,
		arg.TokenHash,
		arg.Type,
		arg.ExpiresAt,
	)
	return err
}

const markVerificationTokenUsed = `-- name: MarkVerificationTokenUsed :exec
UPDATE verification_tokens
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkVerificationTokenUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markVerificationTokenUsed, id)
	return err
}

const updateUserEmailVerified = `-- name: UpdateUserEmailVerified :exec
UPDATE users
SET email_verified_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateUserEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUserEmailVerified, id)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}
