// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlc

import (
	"context"
	"time"
)

const findBillingWebhookEvent = `-- name: FindBillingWebhookEvent :one
SELECT id, provider, event_type, created_at FROM billing_webhook_events
WHERE id = $1
`

func (q *Queries) FindBillingWebhookEvent(ctx context.Context, id string) (BillingWebhookEvent, error) {
	row := q.db.QueryRow(ctx, findBillingWebhookEvent, id)
	var i BillingWebhookEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.EventType,
		&i.CreatedAt,
	)
	return i, err
}

const findPlanPrice = `-- name: FindPlanPrice :one
SELECT plan_id, provider, interval, currency, price_id FROM plan_prices
WHERE plan_id = $1 AND provider = $2 AND interval = $3 AND currency = $4
`

type FindPlanPriceParams struct {
	PlanID   string `json:"plan_id"`
	Provider string `json:"provider"`
	Interval string `json:"interval"`
	Currency string `json:"currency"`
}

func (q *Queries) FindPlanPrice(ctx context.Context, arg FindPlanPriceParams) (PlanPrice, error) {
	row := q.db.QueryRow(ctx, findPlanPrice,
		arg.PlanID,
		arg.Provider,
		arg.Interval,
		arg.Currency,
	)
	var i PlanPrice
	err := row.Scan(
		&i.PlanID,
		&i.Provider,
		&i.Interval,
		&i.Currency,
		&i.PriceID,
	)
	return i, err
}

const findSubscriptionByProviderSub = `-- name: FindSubscriptionByProviderSub :one
SELECT workspace_id, plan_id, provider, provider_customer_id, provider_subscription_id, currency, billing_interval, status, current_period_start, current_period_end, cancel_at_period_end, canceled_at, custom_quotas, custom_features, created_at, updated_at FROM subscriptions
WHERE provider_subscription_id = $1
`

// Webhook path: resolve provider subscription ID → workspace subscription.
func (q *Queries) FindSubscriptionByProviderSub(ctx context.Context, providerSubscriptionID *string) (Subscription, error) {
	row := q.db.QueryRow(ctx, findSubscriptionByProviderSub, providerSubscriptionID)
	var i Subscription
	err := row.Scan(
		&i.WorkspaceID,
		&i.PlanID,
		&i.Provider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.Currency,
		&i.BillingInterval,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CustomQuotas,
		&i.CustomFeatures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findSubscriptionByWorkspace = `-- name: FindSubscriptionByWorkspace :one
SELECT workspace_id, plan_id, provider, provider_customer_id, provider_subscription_id, currency, billing_interval, status, current_period_start, current_period_end, cancel_at_period_end, canceled_at, custom_quotas, custom_features, created_at, updated_at FROM subscriptions
WHERE workspace_id = $1
`

func (q *Queries) FindSubscriptionByWorkspace(ctx context.Context, workspaceID string) (Subscription, error) {
	row := q.db.QueryRow(ctx, findSubscriptionByWorkspace, workspaceID)
	var i Subscription
	err := row.Scan(
		&i.WorkspaceID,
		&i.PlanID,
		&i.Provider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.Currency,
		&i.BillingInterval,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CustomQuotas,
		&i.CustomFeatures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlanPrices = `-- name: ListPlanPrices :many
SELECT plan_id, provider, interval, currency, price_id FROM plan_prices
WHERE provider = $1 AND currency = $2
ORDER BY plan_id, interval
`

type ListPlanPricesParams struct {
	Provider string `json:"provider"`
	Currency string `json:"currency"`
}

func (q *Queries) ListPlanPrices(ctx context.Context, arg ListPlanPricesParams) ([]PlanPrice, error) {
	rows, err := q.db.Query(ctx, listPlanPrices, arg.Provider, arg.Currency)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlanPrice{}
	for rows.Next() {
		var i PlanPrice
		if err := rows.Scan(
			&i.PlanID,
			&i.Provider,
			&i.Interval,
			&i.Currency,
			&i.PriceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBillingWebhookEvent = `-- name: RecordBillingWebhookEvent :exec
INSERT INTO billing_webhook_events (id, provider, event_type)
VALUES ($1, $2, $3)
`

type RecordBillingWebhookEventParams struct {
	ID        string `json:"id"`
	Provider  string `json:"provider"`
	EventType string `json:"event_type"`
}

// Idempotency gatekeeper. PK constraint rejects duplicate event IDs.
func (q *Queries) RecordBillingWebhookEvent(ctx context.Context, arg RecordBillingWebhookEventParams) error {
	_, err := q.db.Exec(ctx, recordBillingWebhookEvent, arg.ID, arg.Provider, arg.EventType)
	return err
}

const syncUsageCycle = `-- name: SyncUsageCycle :execrows
UPDATE workspace_usage SET
    links_usage = 0,
    clicks_usage = 0,
    usage_period_start = $2,
    usage_period_end = $3,
    updated_at = NOW()
WHERE workspace_id = $1
`

type SyncUsageCycleParams struct {
	WorkspaceID      string    `json:"workspace_id"`
	UsagePeriodStart time.Time `json:"usage_period_start"`
	UsagePeriodEnd   time.Time `json:"usage_period_end"`
}

// Webhook path: triggered on new billing cycle.
// Resets consumable counts and bumps the usage period forward.
func (q *Queries) SyncUsageCycle(ctx context.Context, arg SyncUsageCycleParams) (int64, error) {
	result, err := q.db.Exec(ctx, syncUsageCycle, arg.WorkspaceID, arg.UsagePeriodStart, arg.UsagePeriodEnd)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :execrows
UPDATE subscriptions SET
    status = $2,
    canceled_at = $3,
    updated_at = NOW()
WHERE workspace_id = $1
`

type UpdateSubscriptionStatusParams struct {
	WorkspaceID string     `json:"workspace_id"`
	Status      string     `json:"status"`
	CanceledAt  *time.Time `json:"canceled_at"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.WorkspaceID, arg.Status, arg.CanceledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSubscription = `-- name: UpsertSubscription :one
INSERT INTO subscriptions (
    workspace_id, plan_id, provider, provider_customer_id, provider_subscription_id,
    currency, billing_interval, status, current_period_start, current_period_end,
    cancel_at_period_end, canceled_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (workspace_id) DO UPDATE SET
    plan_id = EXCLUDED.plan_id,
    status = EXCLUDED.status,
    current_period_start = EXCLUDED.current_period_start,
    current_period_end = EXCLUDED.current_period_end,
    cancel_at_period_end = EXCLUDED.cancel_at_period_end,
    canceled_at = EXCLUDED.canceled_at,
    updated_at = NOW()
RETURNING workspace_id, plan_id, provider, provider_customer_id, provider_subscription_id, currency, billing_interval, status, current_period_start, current_period_end, cancel_at_period_end, canceled_at, custom_quotas, custom_features, created_at, updated_at
`

type UpsertSubscriptionParams struct {
	WorkspaceID            string     `json:"workspace_id"`
	PlanID                 string     `json:"plan_id"`
	Provider               *string    `json:"provider"`
	ProviderCustomerID     *string    `json:"provider_customer_id"`
	ProviderSubscriptionID *string    `json:"provider_subscription_id"`
	Currency               *string    `json:"currency"`
	BillingInterval        *string    `json:"billing_interval"`
	Status                 string     `json:"status"`
	CurrentPeriodStart     *time.Time `json:"current_period_start"`
	CurrentPeriodEnd       *time.Time `json:"current_period_end"`
	CancelAtPeriodEnd      *bool      `json:"cancel_at_period_end"`
	CanceledAt             *time.Time `json:"canceled_at"`
}

// Webhook path: triggered by subscription lifecycle events.
func (q *Queries) UpsertSubscription(ctx context.Context, arg UpsertSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, upsertSubscription,
		arg.WorkspaceID,
		arg.PlanID,
		arg.Provider,
		arg.ProviderCustomerID,
		arg.ProviderSubscriptionID,
		arg.Currency,
		arg.BillingInterval,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.CancelAtPeriodEnd,
		arg.CanceledAt,
	)
	var i Subscription
	err := row.Scan(
		&i.WorkspaceID,
		&i.PlanID,
		&i.Provider,
		&i.ProviderCustomerID,
		&i.ProviderSubscriptionID,
		&i.Currency,
		&i.BillingInterval,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.CancelAtPeriodEnd,
		&i.CanceledAt,
		&i.CustomQuotas,
		&i.CustomFeatures,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkspaceUsage = `-- name: UpsertWorkspaceUsage :exec
INSERT INTO workspace_usage (workspace_id)
VALUES ($1)
ON CONFLICT (workspace_id) DO NOTHING
`

// Ensures a usage row exists for a workspace (created on first subscription).
func (q *Queries) UpsertWorkspaceUsage(ctx context.Context, workspaceID string) error {
	_, err := q.db.Exec(ctx, upsertWorkspaceUsage, workspaceID)
	return err
}
