// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deep_links.sql

package sqlc

import (
	"context"
)

const deleteDeepLink = `-- name: DeleteDeepLink :execrows
DELETE FROM deep_links
WHERE link_id = $1
`

func (q *Queries) DeleteDeepLink(ctx context.Context, linkID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeepLink, linkID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findDeepLink = `-- name: FindDeepLink :one
SELECT link_id, platform_app_id, workspace_app_id, ios_deep_link, android_deep_link, ios_fallback_url, android_fallback_url, created_at, updated_at FROM deep_links
WHERE link_id = $1
`

func (q *Queries) FindDeepLink(ctx context.Context, linkID string) (DeepLink, error) {
	row := q.db.QueryRow(ctx, findDeepLink, linkID)
	var i DeepLink
	err := row.Scan(
		&i.LinkID,
		&i.PlatformAppID,
		&i.WorkspaceAppID,
		&i.IosDeepLink,
		&i.AndroidDeepLink,
		&i.IosFallbackUrl,
		&i.AndroidFallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resolveDeepLink = `-- name: ResolveDeepLink :one
SELECT
    dl.ios_deep_link,
    dl.android_deep_link,
    COALESCE(dl.ios_fallback_url, wa.app_store_url) AS ios_fallback_url,
    COALESCE(dl.android_fallback_url, wa.play_store_url) AS android_fallback_url,
    COALESCE(pa.android_package, wa.package_name) AS android_package
FROM deep_links dl
LEFT JOIN platform_apps pa ON pa.id = dl.platform_app_id
LEFT JOIN workspace_apps wa ON wa.id = dl.workspace_app_id
WHERE dl.link_id = $1
`

type ResolveDeepLinkRow struct {
	IosDeepLink        *string `json:"ios_deep_link"`
	AndroidDeepLink    *string `json:"android_deep_link"`
	IosFallbackUrl     *string `json:"ios_fallback_url"`
	AndroidFallbackUrl *string `json:"android_fallback_url"`
	AndroidPackage     *string `json:"android_package"`
}

// Redirect path: look up deep link URLs + android package for intent:// URLs.
// One extra round-trip after ResolveLink, only when deepview is needed.
func (q *Queries) ResolveDeepLink(ctx context.Context, linkID string) (ResolveDeepLinkRow, error) {
	row := q.db.QueryRow(ctx, resolveDeepLink, linkID)
	var i ResolveDeepLinkRow
	err := row.Scan(
		&i.IosDeepLink,
		&i.AndroidDeepLink,
		&i.IosFallbackUrl,
		&i.AndroidFallbackUrl,
		&i.AndroidPackage,
	)
	return i, err
}

const upsertDeepLink = `-- name: UpsertDeepLink :one
INSERT INTO deep_links (
    link_id, platform_app_id, workspace_app_id,
    ios_deep_link, android_deep_link,
    ios_fallback_url, android_fallback_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (link_id) DO UPDATE SET
    platform_app_id      = EXCLUDED.platform_app_id,
    workspace_app_id     = EXCLUDED.workspace_app_id,
    ios_deep_link        = EXCLUDED.ios_deep_link,
    android_deep_link    = EXCLUDED.android_deep_link,
    ios_fallback_url     = EXCLUDED.ios_fallback_url,
    android_fallback_url = EXCLUDED.android_fallback_url,
    updated_at           = NOW()
RETURNING link_id, platform_app_id, workspace_app_id, ios_deep_link, android_deep_link, ios_fallback_url, android_fallback_url, created_at, updated_at
`

type UpsertDeepLinkParams struct {
	LinkID             string  `json:"link_id"`
	PlatformAppID      *string `json:"platform_app_id"`
	WorkspaceAppID     *string `json:"workspace_app_id"`
	IosDeepLink        *string `json:"ios_deep_link"`
	AndroidDeepLink    *string `json:"android_deep_link"`
	IosFallbackUrl     *string `json:"ios_fallback_url"`
	AndroidFallbackUrl *string `json:"android_fallback_url"`
}

func (q *Queries) UpsertDeepLink(ctx context.Context, arg UpsertDeepLinkParams) (DeepLink, error) {
	row := q.db.QueryRow(ctx, upsertDeepLink,
		arg.LinkID,
		arg.PlatformAppID,
		arg.WorkspaceAppID,
		arg.IosDeepLink,
		arg.AndroidDeepLink,
		arg.IosFallbackUrl,
		arg.AndroidFallbackUrl,
	)
	var i DeepLink
	err := row.Scan(
		&i.LinkID,
		&i.PlatformAppID,
		&i.WorkspaceAppID,
		&i.IosDeepLink,
		&i.AndroidDeepLink,
		&i.IosFallbackUrl,
		&i.AndroidFallbackUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
