// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entitlement.sql

package sqlc

import (
	"context"
	"time"
)

const findEntitlement = `-- name: FindEntitlement :one
SELECT
    s.plan_id,
    COALESCE(u.links_usage,     0) AS links_usage,
    COALESCE(u.clicks_usage,    0) AS clicks_usage,
    COALESCE(u.domains_active,  0) AS domains_active,
    COALESCE(u.webhooks_active, 0) AS webhooks_active,
    COALESCE(u.api_keys_active, 0) AS api_keys_active,
    COALESCE(u.members_active,  0) AS members_active,
    COALESCE(u.folders_active,  0) AS folders_active,
    COALESCE(u.tags_active,     0) AS tags_active,
    u.usage_period_end
FROM   subscriptions s
LEFT   JOIN workspace_usage u ON u.workspace_id = s.workspace_id
WHERE  s.workspace_id = $1
`

type FindEntitlementRow struct {
	PlanID         string     `json:"plan_id"`
	LinksUsage     int32      `json:"links_usage"`
	ClicksUsage    int64      `json:"clicks_usage"`
	DomainsActive  int32      `json:"domains_active"`
	WebhooksActive int32      `json:"webhooks_active"`
	ApiKeysActive  int32      `json:"api_keys_active"`
	MembersActive  int32      `json:"members_active"`
	FoldersActive  int32      `json:"folders_active"`
	TagsActive     int32      `json:"tags_active"`
	UsagePeriodEnd *time.Time `json:"usage_period_end"`
}

// Workspace existence is already verified by the workspace middleware.
func (q *Queries) FindEntitlement(ctx context.Context, workspaceID string) (FindEntitlementRow, error) {
	row := q.db.QueryRow(ctx, findEntitlement, workspaceID)
	var i FindEntitlementRow
	err := row.Scan(
		&i.PlanID,
		&i.LinksUsage,
		&i.ClicksUsage,
		&i.DomainsActive,
		&i.WebhooksActive,
		&i.ApiKeysActive,
		&i.MembersActive,
		&i.FoldersActive,
		&i.TagsActive,
		&i.UsagePeriodEnd,
	)
	return i, err
}
