// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entitlement.sql

package sqlc

import (
	"context"
)

const findEntitlement = `-- name: FindEntitlement :one
SELECT
    s.plan_id,
    COALESCE(u.links_usage,    0)    AS links_usage,
    COALESCE(u.clicks_usage,   0)    AS clicks_usage,
    (SELECT COUNT(*) FROM domains WHERE domains.workspace_id = $1)::integer AS domains_active,
    (SELECT COUNT(*) FROM workspace_apps WHERE workspace_apps.workspace_id = $1)::integer AS webhooks_active,
    (SELECT COUNT(*) FROM api_keys WHERE api_keys.workspace_id = $1)::integer AS api_keys_active,
    (SELECT COUNT(*) FROM workspace_members WHERE workspace_members.workspace_id = $1)::integer AS members_active,
    (SELECT COUNT(*) FROM folders WHERE folders.workspace_id = $1)::integer AS folders_active,
    (SELECT COUNT(*) FROM tags WHERE tags.workspace_id = $1)::integer AS tags_active
FROM   subscriptions s
LEFT   JOIN workspace_usage u ON u.workspace_id = s.workspace_id
WHERE  s.workspace_id = $1
`

type FindEntitlementRow struct {
	PlanID         string `json:"plan_id"`
	LinksUsage     int32  `json:"links_usage"`
	ClicksUsage    int64  `json:"clicks_usage"`
	DomainsActive  int32  `json:"domains_active"`
	WebhooksActive int32  `json:"webhooks_active"`
	ApiKeysActive  int32  `json:"api_keys_active"`
	MembersActive  int32  `json:"members_active"`
	FoldersActive  int32  `json:"folders_active"`
	TagsActive     int32  `json:"tags_active"`
}

// Middleware hot path: resolves the full entitlement payload for a workspace
// in a single round-trip.
//
// LEFT JOIN ensures workspaces with a subscription but no usage row yet still
// return a row (usage columns will be NULL, coalesced to 0 / '{}').
// If no subscription row exists at all, the query returns no rows — the
// middleware defaults to Free plan + zero usage in that case.
func (q *Queries) FindEntitlement(ctx context.Context, workspaceID string) (FindEntitlementRow, error) {
	row := q.db.QueryRow(ctx, findEntitlement, workspaceID)
	var i FindEntitlementRow
	err := row.Scan(
		&i.PlanID,
		&i.LinksUsage,
		&i.ClicksUsage,
		&i.DomainsActive,
		&i.WebhooksActive,
		&i.ApiKeysActive,
		&i.MembersActive,
		&i.FoldersActive,
		&i.TagsActive,
	)
	return i, err
}
