// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: folders.sql

package sqlc

import (
	"context"
)

const countFoldersByWorkspace = `-- name: CountFoldersByWorkspace :one
SELECT COUNT(*) FROM folders
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountFoldersByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFoldersByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findFolderByID = `-- name: FindFolderByID :one
SELECT id, workspace_id, name, color, position, deleted_at, created_at, updated_at FROM folders
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type FindFolderByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindFolderByID(ctx context.Context, arg FindFolderByIDParams) (Folder, error) {
	row := q.db.QueryRow(ctx, findFolderByID, arg.ID, arg.WorkspaceID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertFolder = `-- name: InsertFolder :one

INSERT INTO folders (
    id, workspace_id, name, color, position
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, workspace_id, name, color, position, deleted_at, created_at, updated_at
`

type InsertFolderParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
	Position    int32  `json:"position"`
}

// Folder queries
func (q *Queries) InsertFolder(ctx context.Context, arg InsertFolderParams) (Folder, error) {
	row := q.db.QueryRow(ctx, insertFolder,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
		arg.Position,
	)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.Position,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFoldersByWorkspace = `-- name: ListFoldersByWorkspace :many
SELECT id, workspace_id, name, color, position, deleted_at, created_at, updated_at FROM folders
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY position, created_at
`

func (q *Queries) ListFoldersByWorkspace(ctx context.Context, workspaceID string) ([]Folder, error) {
	rows, err := q.db.Query(ctx, listFoldersByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.Position,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteFolder = `-- name: SoftDeleteFolder :execrows
UPDATE folders SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SoftDeleteFolderParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteFolder(ctx context.Context, arg SoftDeleteFolderParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteFolder, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
