// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package sqlc

import (
	"context"
	"time"
)

const countLinksByWorkspace = `-- name: CountLinksByWorkspace :one
SELECT COUNT(*) FROM links
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLinksByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countLinksByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findLinkByID = `-- name: FindLinkByID :one
SELECT id, workspace_id, created_by, folder_id, short_code, dest_url, title, description, is_active, starts_at, expires_at, expiration_url, max_clicks, utm_source, utm_medium, utm_campaign, utm_term, utm_content, og_title, og_description, og_image, click_count, unique_click_count, last_clicked_at, notes, created_via, deleted_at, created_at, updated_at FROM links
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type FindLinkByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindLinkByID(ctx context.Context, arg FindLinkByIDParams) (Link, error) {
	row := q.db.QueryRow(ctx, findLinkByID, arg.ID, arg.WorkspaceID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.FolderID,
		&i.ShortCode,
		&i.DestUrl,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirationUrl,
		&i.MaxClicks,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImage,
		&i.ClickCount,
		&i.UniqueClickCount,
		&i.LastClickedAt,
		&i.Notes,
		&i.CreatedVia,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLinkByShortCode = `-- name: FindLinkByShortCode :one
SELECT id, workspace_id, created_by, folder_id, short_code, dest_url, title, description, is_active, starts_at, expires_at, expiration_url, max_clicks, utm_source, utm_medium, utm_campaign, utm_term, utm_content, og_title, og_description, og_image, click_count, unique_click_count, last_clicked_at, notes, created_via, deleted_at, created_at, updated_at FROM links
WHERE short_code = $1 AND deleted_at IS NULL
LIMIT 1
`

// Used by link CRUD lookups. Not on the redirect hot path (see ResolveLink).
func (q *Queries) FindLinkByShortCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, findLinkByShortCode, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.FolderID,
		&i.ShortCode,
		&i.DestUrl,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirationUrl,
		&i.MaxClicks,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImage,
		&i.ClickCount,
		&i.UniqueClickCount,
		&i.LastClickedAt,
		&i.Notes,
		&i.CreatedVia,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRedirectFallback = `-- name: FindRedirectFallback :one
SELECT is_active, starts_at, expires_at, expiration_url, max_clicks, click_count
FROM links
WHERE short_code = $1 AND deleted_at IS NULL
LIMIT 1
`

type FindRedirectFallbackRow struct {
	IsActive      bool       `json:"is_active"`
	StartsAt      *time.Time `json:"starts_at"`
	ExpiresAt     *time.Time `json:"expires_at"`
	ExpirationUrl *string    `json:"expiration_url"`
	MaxClicks     *int32     `json:"max_clicks"`
	ClickCount    int64      `json:"click_count"`
}

// Slim diagnostic query: only called when ResolveLink returns 0 rows.
func (q *Queries) FindRedirectFallback(ctx context.Context, shortCode string) (FindRedirectFallbackRow, error) {
	row := q.db.QueryRow(ctx, findRedirectFallback, shortCode)
	var i FindRedirectFallbackRow
	err := row.Scan(
		&i.IsActive,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirationUrl,
		&i.MaxClicks,
		&i.ClickCount,
	)
	return i, err
}

const insertLink = `-- name: InsertLink :one
INSERT INTO links (
    id, workspace_id, created_by, folder_id, short_code, dest_url, title, description,
    starts_at, expires_at, expiration_url, max_clicks,
    utm_source, utm_medium, utm_campaign, utm_term, utm_content,
    og_title, og_description, og_image,
    notes, created_via
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15, $16, $17,
    $18, $19, $20,
    $21, $22
) RETURNING id, workspace_id, created_by, folder_id, short_code, dest_url, title, description, is_active, starts_at, expires_at, expiration_url, max_clicks, utm_source, utm_medium, utm_campaign, utm_term, utm_content, og_title, og_description, og_image, click_count, unique_click_count, last_clicked_at, notes, created_via, deleted_at, created_at, updated_at
`

type InsertLinkParams struct {
	ID            string     `json:"id"`
	WorkspaceID   string     `json:"workspace_id"`
	CreatedBy     *string    `json:"created_by"`
	FolderID      *string    `json:"folder_id"`
	ShortCode     string     `json:"short_code"`
	DestUrl       string     `json:"dest_url"`
	Title         *string    `json:"title"`
	Description   *string    `json:"description"`
	StartsAt      *time.Time `json:"starts_at"`
	ExpiresAt     *time.Time `json:"expires_at"`
	ExpirationUrl *string    `json:"expiration_url"`
	MaxClicks     *int32     `json:"max_clicks"`
	UtmSource     *string    `json:"utm_source"`
	UtmMedium     *string    `json:"utm_medium"`
	UtmCampaign   *string    `json:"utm_campaign"`
	UtmTerm       *string    `json:"utm_term"`
	UtmContent    *string    `json:"utm_content"`
	OgTitle       *string    `json:"og_title"`
	OgDescription *string    `json:"og_description"`
	OgImage       *string    `json:"og_image"`
	Notes         *string    `json:"notes"`
	CreatedVia    string     `json:"created_via"`
}

func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, insertLink,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.FolderID,
		arg.ShortCode,
		arg.DestUrl,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.ExpiresAt,
		arg.ExpirationUrl,
		arg.MaxClicks,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
		arg.UtmTerm,
		arg.UtmContent,
		arg.OgTitle,
		arg.OgDescription,
		arg.OgImage,
		arg.Notes,
		arg.CreatedVia,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.FolderID,
		&i.ShortCode,
		&i.DestUrl,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.StartsAt,
		&i.ExpiresAt,
		&i.ExpirationUrl,
		&i.MaxClicks,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImage,
		&i.ClickCount,
		&i.UniqueClickCount,
		&i.LastClickedAt,
		&i.Notes,
		&i.CreatedVia,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLinksByWorkspace = `-- name: ListLinksByWorkspace :many
SELECT id, workspace_id, created_by, folder_id, short_code, dest_url, title, description, is_active, starts_at, expires_at, expiration_url, max_clicks, utm_source, utm_medium, utm_campaign, utm_term, utm_content, og_title, og_description, og_image, click_count, unique_click_count, last_clicked_at, notes, created_via, deleted_at, created_at, updated_at FROM links
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLinksByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListLinksByWorkspace(ctx context.Context, arg ListLinksByWorkspaceParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinksByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.FolderID,
			&i.ShortCode,
			&i.DestUrl,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.StartsAt,
			&i.ExpiresAt,
			&i.ExpirationUrl,
			&i.MaxClicks,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
			&i.UtmTerm,
			&i.UtmContent,
			&i.OgTitle,
			&i.OgDescription,
			&i.OgImage,
			&i.ClickCount,
			&i.UniqueClickCount,
			&i.LastClickedAt,
			&i.Notes,
			&i.CreatedVia,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveLink = `-- name: ResolveLink :one
UPDATE links SET
    click_count = click_count + 1,
    last_clicked_at = NOW()
WHERE short_code = $1
    AND deleted_at IS NULL
    AND is_active = TRUE
    AND (starts_at IS NULL OR starts_at <= NOW())
    AND (expires_at IS NULL OR expires_at > NOW())
    AND (max_clicks IS NULL OR click_count < max_clicks)
RETURNING id, dest_url,
    utm_source, utm_medium, utm_campaign, utm_term, utm_content,
    og_title, og_description, og_image
`

type ResolveLinkRow struct {
	ID            string  `json:"id"`
	DestUrl       string  `json:"dest_url"`
	UtmSource     *string `json:"utm_source"`
	UtmMedium     *string `json:"utm_medium"`
	UtmCampaign   *string `json:"utm_campaign"`
	UtmTerm       *string `json:"utm_term"`
	UtmContent    *string `json:"utm_content"`
	OgTitle       *string `json:"og_title"`
	OgDescription *string `json:"og_description"`
	OgImage       *string `json:"og_image"`
}

// Redirect hot path: atomic increment + return in one round-trip.
// Returns no rows when the link is invalid (deleted, inactive, expired, not started, or click-limited).
func (q *Queries) ResolveLink(ctx context.Context, shortCode string) (ResolveLinkRow, error) {
	row := q.db.QueryRow(ctx, resolveLink, shortCode)
	var i ResolveLinkRow
	err := row.Scan(
		&i.ID,
		&i.DestUrl,
		&i.UtmSource,
		&i.UtmMedium,
		&i.UtmCampaign,
		&i.UtmTerm,
		&i.UtmContent,
		&i.OgTitle,
		&i.OgDescription,
		&i.OgImage,
	)
	return i, err
}

const softDeleteLink = `-- name: SoftDeleteLink :execrows
UPDATE links SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLinkParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteLink(ctx context.Context, arg SoftDeleteLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLink, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
