// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package sqlc

import (
	"context"
	"time"
)

const countLinksByWorkspace = `-- name: CountLinksByWorkspace :one
SELECT COUNT(*) FROM links
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountLinksByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countLinksByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findLinkByID = `-- name: FindLinkByID :one
SELECT id, workspace_id, short_code, dest_url, title, description, is_active, expires_at, click_count, last_clicked_at, deleted_at, created_at, updated_at FROM links
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
LIMIT 1
`

type FindLinkByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindLinkByID(ctx context.Context, arg FindLinkByIDParams) (Link, error) {
	row := q.db.QueryRow(ctx, findLinkByID, arg.ID, arg.WorkspaceID)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShortCode,
		&i.DestUrl,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.ExpiresAt,
		&i.ClickCount,
		&i.LastClickedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findLinkByShortCode = `-- name: FindLinkByShortCode :one
SELECT id, workspace_id, short_code, dest_url, title, description, is_active, expires_at, click_count, last_clicked_at, deleted_at, created_at, updated_at FROM links
WHERE short_code = $1 AND deleted_at IS NULL
LIMIT 1
`

// Redirect hot path. Uses covering index idx_links_redirect.
func (q *Queries) FindLinkByShortCode(ctx context.Context, shortCode string) (Link, error) {
	row := q.db.QueryRow(ctx, findLinkByShortCode, shortCode)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShortCode,
		&i.DestUrl,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.ExpiresAt,
		&i.ClickCount,
		&i.LastClickedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertLink = `-- name: InsertLink :one

INSERT INTO links (
    id, workspace_id, short_code, dest_url, title, description, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, workspace_id, short_code, dest_url, title, description, is_active, expires_at, click_count, last_clicked_at, deleted_at, created_at, updated_at
`

type InsertLinkParams struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	ShortCode   string     `json:"short_code"`
	DestUrl     string     `json:"dest_url"`
	Title       *string    `json:"title"`
	Description *string    `json:"description"`
	ExpiresAt   *time.Time `json:"expires_at"`
}

// Link queries
func (q *Queries) InsertLink(ctx context.Context, arg InsertLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, insertLink,
		arg.ID,
		arg.WorkspaceID,
		arg.ShortCode,
		arg.DestUrl,
		arg.Title,
		arg.Description,
		arg.ExpiresAt,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShortCode,
		&i.DestUrl,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.ExpiresAt,
		&i.ClickCount,
		&i.LastClickedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLinksByWorkspace = `-- name: ListLinksByWorkspace :many
SELECT id, workspace_id, short_code, dest_url, title, description, is_active, expires_at, click_count, last_clicked_at, deleted_at, created_at, updated_at FROM links
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLinksByWorkspaceParams struct {
	WorkspaceID string `json:"workspace_id"`
	Limit       int32  `json:"limit"`
	Offset      int32  `json:"offset"`
}

func (q *Queries) ListLinksByWorkspace(ctx context.Context, arg ListLinksByWorkspaceParams) ([]Link, error) {
	rows, err := q.db.Query(ctx, listLinksByWorkspace, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Link{}
	for rows.Next() {
		var i Link
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ShortCode,
			&i.DestUrl,
			&i.Title,
			&i.Description,
			&i.IsActive,
			&i.ExpiresAt,
			&i.ClickCount,
			&i.LastClickedAt,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLink = `-- name: SoftDeleteLink :execrows
UPDATE links SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SoftDeleteLinkParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteLink(ctx context.Context, arg SoftDeleteLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLink, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links SET
    dest_url = COALESCE($1, dest_url),
    title = COALESCE($2, title),
    description = COALESCE($3, description),
    is_active = COALESCE($4, is_active),
    expires_at = CASE WHEN $5::BOOLEAN THEN $6 ELSE expires_at END,
    updated_at = NOW()
WHERE id = $7 AND workspace_id = $8 AND deleted_at IS NULL
RETURNING id, workspace_id, short_code, dest_url, title, description, is_active, expires_at, click_count, last_clicked_at, deleted_at, created_at, updated_at
`

type UpdateLinkParams struct {
	DestUrl      *string    `json:"dest_url"`
	Title        *string    `json:"title"`
	Description  *string    `json:"description"`
	IsActive     *bool      `json:"is_active"`
	SetExpiresAt bool       `json:"set_expires_at"`
	ExpiresAt    *time.Time `json:"expires_at"`
	ID           string     `json:"id"`
	WorkspaceID  string     `json:"workspace_id"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error) {
	row := q.db.QueryRow(ctx, updateLink,
		arg.DestUrl,
		arg.Title,
		arg.Description,
		arg.IsActive,
		arg.SetExpiresAt,
		arg.ExpiresAt,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Link
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.ShortCode,
		&i.DestUrl,
		&i.Title,
		&i.Description,
		&i.IsActive,
		&i.ExpiresAt,
		&i.ClickCount,
		&i.LastClickedAt,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
