// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"
	"time"
)

type Account struct {
	ID                string    `json:"id"`
	UserID            string    `json:"user_id"`
	Provider          string    `json:"provider"`
	ProviderAccountID string    `json:"provider_account_id"`
	PasswordHash      *string   `json:"password_hash"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type ApiKey struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	CreatedBy   *string    `json:"created_by"`
	Name        string     `json:"name"`
	KeyHash     string     `json:"key_hash"`
	KeyPrefix   string     `json:"key_prefix"`
	Permission  string     `json:"permission"`
	Scopes      []string   `json:"scopes"`
	ExpiresAt   *time.Time `json:"expires_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type BillingWebhookEvent struct {
	ID        string    `json:"id"`
	Provider  string    `json:"provider"`
	EventType string    `json:"event_type"`
	CreatedAt time.Time `json:"created_at"`
}

type Folder struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	CreatedBy   *string    `json:"created_by"`
	Name        string     `json:"name"`
	Color       string     `json:"color"`
	Position    int32      `json:"position"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type Link struct {
	ID               string     `json:"id"`
	WorkspaceID      string     `json:"workspace_id"`
	CreatedBy        *string    `json:"created_by"`
	FolderID         *string    `json:"folder_id"`
	ShortCode        string     `json:"short_code"`
	DestUrl          string     `json:"dest_url"`
	Title            *string    `json:"title"`
	Description      *string    `json:"description"`
	IsActive         bool       `json:"is_active"`
	StartsAt         *time.Time `json:"starts_at"`
	ExpiresAt        *time.Time `json:"expires_at"`
	ExpirationUrl    *string    `json:"expiration_url"`
	MaxClicks        *int32     `json:"max_clicks"`
	UtmSource        *string    `json:"utm_source"`
	UtmMedium        *string    `json:"utm_medium"`
	UtmCampaign      *string    `json:"utm_campaign"`
	UtmTerm          *string    `json:"utm_term"`
	UtmContent       *string    `json:"utm_content"`
	OgTitle          *string    `json:"og_title"`
	OgDescription    *string    `json:"og_description"`
	OgImage          *string    `json:"og_image"`
	ClickCount       int64      `json:"click_count"`
	UniqueClickCount int64      `json:"unique_click_count"`
	LastClickedAt    *time.Time `json:"last_clicked_at"`
	Notes            *string    `json:"notes"`
	CreatedVia       string     `json:"created_via"`
	DeletedAt        *time.Time `json:"deleted_at"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
}

type LinkTag struct {
	LinkID    string    `json:"link_id"`
	TagID     string    `json:"tag_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Plan struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type PlanPrice struct {
	PlanID   string `json:"plan_id"`
	Provider string `json:"provider"`
	Interval string `json:"interval"`
	Currency string `json:"currency"`
	PriceID  string `json:"price_id"`
}

type Session struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Subscription struct {
	WorkspaceID            string     `json:"workspace_id"`
	PlanID                 string     `json:"plan_id"`
	Provider               *string    `json:"provider"`
	ProviderCustomerID     *string    `json:"provider_customer_id"`
	ProviderSubscriptionID *string    `json:"provider_subscription_id"`
	Currency               *string    `json:"currency"`
	BillingInterval        *string    `json:"billing_interval"`
	Status                 string     `json:"status"`
	CurrentPeriodStart     *time.Time `json:"current_period_start"`
	CurrentPeriodEnd       *time.Time `json:"current_period_end"`
	CancelAtPeriodEnd      *bool      `json:"cancel_at_period_end"`
	CanceledAt             *time.Time `json:"canceled_at"`
	CustomQuotas           []byte     `json:"custom_quotas"`
	CustomFeatures         []byte     `json:"custom_features"`
	CreatedAt              time.Time  `json:"created_at"`
	UpdatedAt              time.Time  `json:"updated_at"`
}

type Tag struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	CreatedBy   *string    `json:"created_by"`
	Name        string     `json:"name"`
	Color       string     `json:"color"`
	DeletedAt   *time.Time `json:"deleted_at"`
	CreatedAt   time.Time  `json:"created_at"`
	UpdatedAt   time.Time  `json:"updated_at"`
}

type User struct {
	ID              string     `json:"id"`
	Name            string     `json:"name"`
	Email           string     `json:"email"`
	EmailVerifiedAt *time.Time `json:"email_verified_at"`
	AvatarUrl       *string    `json:"avatar_url"`
	Status          string     `json:"status"`
	OnboardedAt     *time.Time `json:"onboarded_at"`
	LastLoginAt     *time.Time `json:"last_login_at"`
	Timezone        string     `json:"timezone"`
	DeletedAt       *time.Time `json:"deleted_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type VerificationToken struct {
	ID        string     `json:"id"`
	UserID    string     `json:"user_id"`
	Email     string     `json:"email"`
	TokenHash string     `json:"token_hash"`
	Type      string     `json:"type"`
	ExpiresAt time.Time  `json:"expires_at"`
	UsedAt    *time.Time `json:"used_at"`
	CreatedAt time.Time  `json:"created_at"`
}

type Workspace struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	DeletedAt *time.Time `json:"deleted_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
}

type WorkspaceInvitation struct {
	ID          string     `json:"id"`
	WorkspaceID string     `json:"workspace_id"`
	Email       string     `json:"email"`
	Role        string     `json:"role"`
	TokenHash   string     `json:"token_hash"`
	InvitedBy   *string    `json:"invited_by"`
	ExpiresAt   time.Time  `json:"expires_at"`
	AcceptedAt  *time.Time `json:"accepted_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type WorkspaceMember struct {
	WorkspaceID string    `json:"workspace_id"`
	UserID      string    `json:"user_id"`
	Role        string    `json:"role"`
	InvitedBy   *string   `json:"invited_by"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type WorkspaceUsage struct {
	WorkspaceID      string          `json:"workspace_id"`
	LinksUsage       int32           `json:"links_usage"`
	ClicksUsage      int64           `json:"clicks_usage"`
	DomainsActive    int32           `json:"domains_active"`
	WebhooksActive   int32           `json:"webhooks_active"`
	ApiKeysActive    int32           `json:"api_keys_active"`
	MembersActive    int32           `json:"members_active"`
	FoldersActive    int32           `json:"folders_active"`
	TagsActive       int32           `json:"tags_active"`
	OverQuota        json.RawMessage `json:"over_quota"`
	UsagePeriodStart time.Time       `json:"usage_period_start"`
	UsagePeriodEnd   time.Time       `json:"usage_period_end"`
	CreatedAt        time.Time       `json:"created_at"`
	UpdatedAt        time.Time       `json:"updated_at"`
}
