// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: platform_apps.sql

package sqlc

import (
	"context"
)

const findPlatformAppByID = `-- name: FindPlatformAppByID :one
SELECT id, name, icon_url, url_patterns, ios_scheme, android_scheme, ios_app_id, ios_bundle_id, ios_team_id, android_package, android_sha256, created_at, updated_at FROM platform_apps
WHERE id = $1
`

func (q *Queries) FindPlatformAppByID(ctx context.Context, id string) (PlatformApp, error) {
	row := q.db.QueryRow(ctx, findPlatformAppByID, id)
	var i PlatformApp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IconUrl,
		&i.UrlPatterns,
		&i.IosScheme,
		&i.AndroidScheme,
		&i.IosAppID,
		&i.IosBundleID,
		&i.IosTeamID,
		&i.AndroidPackage,
		&i.AndroidSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findPlatformAppByURLPattern = `-- name: FindPlatformAppByURLPattern :one
SELECT id, name, icon_url, url_patterns, ios_scheme, android_scheme, ios_app_id, ios_bundle_id, ios_team_id, android_package, android_sha256, created_at, updated_at FROM platform_apps
WHERE url_patterns @> ARRAY[$1::TEXT]
LIMIT 1
`

// Finds the first platform app whose url_patterns array contains the given hostname.
func (q *Queries) FindPlatformAppByURLPattern(ctx context.Context, dollar_1 string) (PlatformApp, error) {
	row := q.db.QueryRow(ctx, findPlatformAppByURLPattern, dollar_1)
	var i PlatformApp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IconUrl,
		&i.UrlPatterns,
		&i.IosScheme,
		&i.AndroidScheme,
		&i.IosAppID,
		&i.IosBundleID,
		&i.IosTeamID,
		&i.AndroidPackage,
		&i.AndroidSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPlatformApp = `-- name: InsertPlatformApp :one
INSERT INTO platform_apps (
    id, name, icon_url, url_patterns,
    ios_scheme, android_scheme,
    ios_app_id, ios_bundle_id, ios_team_id,
    android_package, android_sha256
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9,
    $10, $11
) RETURNING id, name, icon_url, url_patterns, ios_scheme, android_scheme, ios_app_id, ios_bundle_id, ios_team_id, android_package, android_sha256, created_at, updated_at
`

type InsertPlatformAppParams struct {
	ID             string   `json:"id"`
	Name           string   `json:"name"`
	IconUrl        *string  `json:"icon_url"`
	UrlPatterns    []string `json:"url_patterns"`
	IosScheme      *string  `json:"ios_scheme"`
	AndroidScheme  *string  `json:"android_scheme"`
	IosAppID       *string  `json:"ios_app_id"`
	IosBundleID    *string  `json:"ios_bundle_id"`
	IosTeamID      *string  `json:"ios_team_id"`
	AndroidPackage *string  `json:"android_package"`
	AndroidSha256  []string `json:"android_sha256"`
}

func (q *Queries) InsertPlatformApp(ctx context.Context, arg InsertPlatformAppParams) (PlatformApp, error) {
	row := q.db.QueryRow(ctx, insertPlatformApp,
		arg.ID,
		arg.Name,
		arg.IconUrl,
		arg.UrlPatterns,
		arg.IosScheme,
		arg.AndroidScheme,
		arg.IosAppID,
		arg.IosBundleID,
		arg.IosTeamID,
		arg.AndroidPackage,
		arg.AndroidSha256,
	)
	var i PlatformApp
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IconUrl,
		&i.UrlPatterns,
		&i.IosScheme,
		&i.AndroidScheme,
		&i.IosAppID,
		&i.IosBundleID,
		&i.IosTeamID,
		&i.AndroidPackage,
		&i.AndroidSha256,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlatformApps = `-- name: ListPlatformApps :many
SELECT id, name, icon_url, url_patterns, ios_scheme, android_scheme, ios_app_id, ios_bundle_id, ios_team_id, android_package, android_sha256, created_at, updated_at FROM platform_apps
ORDER BY name
`

func (q *Queries) ListPlatformApps(ctx context.Context) ([]PlatformApp, error) {
	rows, err := q.db.Query(ctx, listPlatformApps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformApp{}
	for rows.Next() {
		var i PlatformApp
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IconUrl,
			&i.UrlPatterns,
			&i.IosScheme,
			&i.AndroidScheme,
			&i.IosAppID,
			&i.IosBundleID,
			&i.IosTeamID,
			&i.AndroidPackage,
			&i.AndroidSha256,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
