// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
)

const addTagToLink = `-- name: AddTagToLink :exec

INSERT INTO link_tags (link_id, tag_id)
SELECT l.id, t.id
FROM links l, tags t
WHERE l.id = $1 AND t.id = $2
  AND l.workspace_id = $3 AND t.workspace_id = $3
  AND l.deleted_at IS NULL AND t.deleted_at IS NULL
ON CONFLICT (link_id, tag_id) DO NOTHING
`

type AddTagToLinkParams struct {
	LinkID      string `json:"link_id"`
	TagID       string `json:"tag_id"`
	WorkspaceID string `json:"workspace_id"`
}

// Link-tag association
func (q *Queries) AddTagToLink(ctx context.Context, arg AddTagToLinkParams) error {
	_, err := q.db.Exec(ctx, addTagToLink, arg.LinkID, arg.TagID, arg.WorkspaceID)
	return err
}

const findTagByID = `-- name: FindTagByID :one
SELECT id, workspace_id, created_by, name, color, deleted_at, created_at, updated_at FROM tags
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type FindTagByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindTagByID(ctx context.Context, arg FindTagByIDParams) (Tag, error) {
	row := q.db.QueryRow(ctx, findTagByID, arg.ID, arg.WorkspaceID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Name,
		&i.Color,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one
INSERT INTO tags (
    id, workspace_id, created_by, name, color
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, workspace_id, created_by, name, color, deleted_at, created_at, updated_at
`

type InsertTagParams struct {
	ID          string  `json:"id"`
	WorkspaceID string  `json:"workspace_id"`
	CreatedBy   *string `json:"created_by"`
	Name        string  `json:"name"`
	Color       string  `json:"color"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.Name,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Name,
		&i.Color,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTagsByLink = `-- name: ListTagsByLink :many
SELECT t.id, t.workspace_id, t.created_by, t.name, t.color, t.deleted_at, t.created_at, t.updated_at FROM tags t
JOIN link_tags lt ON lt.tag_id = t.id
JOIN links l ON l.id = lt.link_id
WHERE lt.link_id = $1 AND l.workspace_id = $2
  AND t.deleted_at IS NULL AND l.deleted_at IS NULL
ORDER BY t.name
`

type ListTagsByLinkParams struct {
	LinkID      string `json:"link_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) ListTagsByLink(ctx context.Context, arg ListTagsByLinkParams) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByLink, arg.LinkID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.Name,
			&i.Color,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByWorkspace = `-- name: ListTagsByWorkspace :many
SELECT id, workspace_id, created_by, name, color, deleted_at, created_at, updated_at FROM tags
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListTagsByWorkspace(ctx context.Context, workspaceID string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.Name,
			&i.Color,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromLink = `-- name: RemoveTagFromLink :execrows
DELETE FROM link_tags lt
USING links l, tags t
WHERE lt.link_id = l.id AND lt.tag_id = t.id
  AND lt.link_id = $1 AND lt.tag_id = $2
  AND l.workspace_id = $3 AND t.workspace_id = $3
`

type RemoveTagFromLinkParams struct {
	LinkID      string `json:"link_id"`
	TagID       string `json:"tag_id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) RemoveTagFromLink(ctx context.Context, arg RemoveTagFromLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTagFromLink, arg.LinkID, arg.TagID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteTag = `-- name: SoftDeleteTag :execrows
UPDATE tags SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTagParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteTag(ctx context.Context, arg SoftDeleteTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTag, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
