// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tags.sql

package sqlc

import (
	"context"
)

const addTagToLink = `-- name: AddTagToLink :exec

INSERT INTO link_tags (link_id, tag_id)
VALUES ($1, $2)
ON CONFLICT (link_id, tag_id) DO NOTHING
`

type AddTagToLinkParams struct {
	LinkID string `json:"link_id"`
	TagID  string `json:"tag_id"`
}

// Link-tag association
func (q *Queries) AddTagToLink(ctx context.Context, arg AddTagToLinkParams) error {
	_, err := q.db.Exec(ctx, addTagToLink, arg.LinkID, arg.TagID)
	return err
}

const countTagsByWorkspace = `-- name: CountTagsByWorkspace :one
SELECT COUNT(*) FROM tags
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountTagsByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countTagsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findTagByID = `-- name: FindTagByID :one
SELECT id, workspace_id, name, color, deleted_at, created_at, updated_at FROM tags
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type FindTagByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindTagByID(ctx context.Context, arg FindTagByIDParams) (Tag, error) {
	row := q.db.QueryRow(ctx, findTagByID, arg.ID, arg.WorkspaceID)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertTag = `-- name: InsertTag :one

INSERT INTO tags (
    id, workspace_id, name, color
) VALUES (
    $1, $2, $3, $4
) RETURNING id, workspace_id, name, color, deleted_at, created_at, updated_at
`

type InsertTagParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
	Name        string `json:"name"`
	Color       string `json:"color"`
}

// Tag queries
func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) (Tag, error) {
	row := q.db.QueryRow(ctx, insertTag,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Color,
	)
	var i Tag
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Color,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLinkIDsByTag = `-- name: ListLinkIDsByTag :many
SELECT lt.link_id FROM link_tags lt
JOIN tags t ON t.id = lt.tag_id
WHERE lt.tag_id = $1 AND t.deleted_at IS NULL
`

func (q *Queries) ListLinkIDsByTag(ctx context.Context, tagID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listLinkIDsByTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var link_id string
		if err := rows.Scan(&link_id); err != nil {
			return nil, err
		}
		items = append(items, link_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByLink = `-- name: ListTagsByLink :many
SELECT t.id, t.workspace_id, t.name, t.color, t.deleted_at, t.created_at, t.updated_at FROM tags t
JOIN link_tags lt ON lt.tag_id = t.id
WHERE lt.link_id = $1 AND t.deleted_at IS NULL
ORDER BY t.name
`

func (q *Queries) ListTagsByLink(ctx context.Context, linkID string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByLink, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsByWorkspace = `-- name: ListTagsByWorkspace :many
SELECT id, workspace_id, name, color, deleted_at, created_at, updated_at FROM tags
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListTagsByWorkspace(ctx context.Context, workspaceID string) ([]Tag, error) {
	rows, err := q.db.Query(ctx, listTagsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Color,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromLink = `-- name: RemoveTagFromLink :execrows
DELETE FROM link_tags
WHERE link_id = $1 AND tag_id = $2
`

type RemoveTagFromLinkParams struct {
	LinkID string `json:"link_id"`
	TagID  string `json:"tag_id"`
}

func (q *Queries) RemoveTagFromLink(ctx context.Context, arg RemoveTagFromLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTagFromLink, arg.LinkID, arg.TagID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLinkTags = `-- name: SetLinkTags :exec
DELETE FROM link_tags WHERE link_id = $1
`

// Replace all tags on a link. Called within a transaction:
// 1. DELETE FROM link_tags WHERE link_id = $1
// 2. INSERT each new tag
// This query handles step 1.
func (q *Queries) SetLinkTags(ctx context.Context, linkID string) error {
	_, err := q.db.Exec(ctx, setLinkTags, linkID)
	return err
}

const softDeleteTag = `-- name: SoftDeleteTag :execrows
UPDATE tags SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTagParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteTag(ctx context.Context, arg SoftDeleteTagParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTag, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
