// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage.sql

package sqlc

import (
	"context"
)

const incrementUsage = `-- name: IncrementUsage :execrows
UPDATE workspace_usage SET
    links_usage = CASE WHEN $2::BOOLEAN THEN links_usage + $3::INT ELSE links_usage END,
    clicks_usage = CASE WHEN $4::BOOLEAN THEN clicks_usage + $3::BIGINT ELSE clicks_usage END,
    updated_at = NOW()
WHERE workspace_id = $1
  AND usage_period_end > NOW()
  AND EXISTS (SELECT 1 FROM workspaces WHERE id = $1 AND deleted_at IS NULL)
`

type IncrementUsageParams struct {
	WorkspaceID string `json:"workspace_id"`
	IsLinks     bool   `json:"is_links"`
	Delta       int32  `json:"delta"`
	IsClicks    bool   `json:"is_clicks"`
}

func (q *Queries) IncrementUsage(ctx context.Context, arg IncrementUsageParams) (int64, error) {
	result, err := q.db.Exec(ctx, incrementUsage,
		arg.WorkspaceID,
		arg.IsLinks,
		arg.Delta,
		arg.IsClicks,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rolloverUsageCycle = `-- name: RolloverUsageCycle :execrows
UPDATE workspace_usage SET
    links_usage = 0,
    clicks_usage = 0,
    usage_period_start = usage_period_end,
    usage_period_end = usage_period_end + interval '1 month',
    updated_at = NOW()
WHERE workspace_id = $1 AND usage_period_end <= NOW()
`

// Resets consumable counters natively when the exact billing anniversary period has expired.
// No-op if the cycle is still active (idempotent).
func (q *Queries) RolloverUsageCycle(ctx context.Context, workspaceID string) (int64, error) {
	result, err := q.db.Exec(ctx, rolloverUsageCycle, workspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertWorkspaceUsage = `-- name: UpsertWorkspaceUsage :exec
INSERT INTO workspace_usage (workspace_id)
VALUES ($1)
ON CONFLICT (workspace_id) DO NOTHING
`

func (q *Queries) UpsertWorkspaceUsage(ctx context.Context, workspaceID string) error {
	_, err := q.db.Exec(ctx, upsertWorkspaceUsage, workspaceID)
	return err
}
