// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace.sql

package sqlc

import (
	"context"
	"time"
)

const acceptWorkspaceInvitation = `-- name: AcceptWorkspaceInvitation :exec
UPDATE workspace_invitations
SET accepted_at = NOW()
WHERE id = $1
`

func (q *Queries) AcceptWorkspaceInvitation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, acceptWorkspaceInvitation, id)
	return err
}

const countWorkspaceOwners = `-- name: CountWorkspaceOwners :one
SELECT COUNT(*)::int FROM workspace_members
WHERE workspace_id = $1 AND role = 'owner'
`

func (q *Queries) CountWorkspaceOwners(ctx context.Context, workspaceID string) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkspaceOwners, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWorkspaceInvitation = `-- name: DeleteWorkspaceInvitation :exec
DELETE FROM workspace_invitations
WHERE id = $1 AND workspace_id = $2
`

type DeleteWorkspaceInvitationParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) DeleteWorkspaceInvitation(ctx context.Context, arg DeleteWorkspaceInvitationParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceInvitation, arg.ID, arg.WorkspaceID)
	return err
}

const deleteWorkspaceMember = `-- name: DeleteWorkspaceMember :exec
DELETE FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type DeleteWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) DeleteWorkspaceMember(ctx context.Context, arg DeleteWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceMember, arg.WorkspaceID, arg.UserID)
	return err
}

const findWorkspaceByID = `-- name: FindWorkspaceByID :one
SELECT id, name, slug, status, deleted_at, created_at, updated_at FROM workspaces
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) FindWorkspaceByID(ctx context.Context, id string) (Workspace, error) {
	row := q.db.QueryRow(ctx, findWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWorkspaceBySlug = `-- name: FindWorkspaceBySlug :one
SELECT id, name, slug, status, deleted_at, created_at, updated_at FROM workspaces
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) FindWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error) {
	row := q.db.QueryRow(ctx, findWorkspaceBySlug, slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findWorkspaceBySlugAndMember = `-- name: FindWorkspaceBySlugAndMember :one

SELECT
    w.id, w.name, w.slug, w.status, w.deleted_at, w.created_at, w.updated_at,
    wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id AND wm.user_id = $1
WHERE w.slug = $2 AND w.deleted_at IS NULL
`

type FindWorkspaceBySlugAndMemberParams struct {
	UserID string `json:"user_id"`
	Slug   string `json:"slug"`
}

type FindWorkspaceBySlugAndMemberRow struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	Status    string     `json:"status"`
	DeletedAt *time.Time `json:"deleted_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	Role      string     `json:"role"`
}

// Workspace members
// Middleware hot path: resolve workspace and member role in one round-trip.
func (q *Queries) FindWorkspaceBySlugAndMember(ctx context.Context, arg FindWorkspaceBySlugAndMemberParams) (FindWorkspaceBySlugAndMemberRow, error) {
	row := q.db.QueryRow(ctx, findWorkspaceBySlugAndMember, arg.UserID, arg.Slug)
	var i FindWorkspaceBySlugAndMemberRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
	)
	return i, err
}

const findWorkspaceInvitationByTokenHash = `-- name: FindWorkspaceInvitationByTokenHash :one
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM workspace_invitations
WHERE token_hash = $1
  AND accepted_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) FindWorkspaceInvitationByTokenHash(ctx context.Context, tokenHash string) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, findWorkspaceInvitationByTokenHash, tokenHash)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const findWorkspaceMember = `-- name: FindWorkspaceMember :one
SELECT workspace_id, user_id, role, invited_by, created_at, updated_at FROM workspace_members
WHERE workspace_id = $1 AND user_id = $2
`

type FindWorkspaceMemberParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
}

func (q *Queries) FindWorkspaceMember(ctx context.Context, arg FindWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, findWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspace = `-- name: InsertWorkspace :one
INSERT INTO workspaces (id, name, slug, status)
VALUES ($1, $2, $3, $4)
RETURNING id, name, slug, status, deleted_at, created_at, updated_at
`

type InsertWorkspaceParams struct {
	ID     string `json:"id"`
	Name   string `json:"name"`
	Slug   string `json:"slug"`
	Status string `json:"status"`
}

func (q *Queries) InsertWorkspace(ctx context.Context, arg InsertWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, insertWorkspace,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.Status,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspaceInvitation = `-- name: InsertWorkspaceInvitation :one

INSERT INTO workspace_invitations (id, workspace_id, email, role, token_hash, invited_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at
`

type InsertWorkspaceInvitationParams struct {
	ID          string    `json:"id"`
	WorkspaceID string    `json:"workspace_id"`
	Email       string    `json:"email"`
	Role        string    `json:"role"`
	TokenHash   string    `json:"token_hash"`
	InvitedBy   *string   `json:"invited_by"`
	ExpiresAt   time.Time `json:"expires_at"`
}

// Workspace invitations
func (q *Queries) InsertWorkspaceInvitation(ctx context.Context, arg InsertWorkspaceInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceInvitation,
		arg.ID,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkspaceMember = `-- name: InsertWorkspaceMember :exec
INSERT INTO workspace_members (workspace_id, user_id, role, invited_by)
VALUES ($1, $2, $3, $4)
`

type InsertWorkspaceMemberParams struct {
	WorkspaceID string  `json:"workspace_id"`
	UserID      string  `json:"user_id"`
	Role        string  `json:"role"`
	InvitedBy   *string `json:"invited_by"`
}

func (q *Queries) InsertWorkspaceMember(ctx context.Context, arg InsertWorkspaceMemberParams) error {
	_, err := q.db.Exec(ctx, insertWorkspaceMember,
		arg.WorkspaceID,
		arg.UserID,
		arg.Role,
		arg.InvitedBy,
	)
	return err
}

const listOwnedWorkspacePlans = `-- name: ListOwnedWorkspacePlans :many
SELECT COALESCE(s.plan_id, 'free')::TEXT AS plan_id
FROM workspace_members wm
JOIN workspaces w ON w.id = wm.workspace_id
LEFT JOIN subscriptions s ON s.workspace_id = wm.workspace_id
WHERE wm.user_id = $1 AND wm.role = 'owner' AND w.status = 'active' AND w.deleted_at IS NULL
`

func (q *Queries) ListOwnedWorkspacePlans(ctx context.Context, userID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listOwnedWorkspacePlans, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var plan_id string
		if err := rows.Scan(&plan_id); err != nil {
			return nil, err
		}
		items = append(items, plan_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceInvitations = `-- name: ListWorkspaceInvitations :many
SELECT id, workspace_id, email, role, token_hash, invited_by, expires_at, accepted_at, created_at FROM workspace_invitations
WHERE workspace_id = $1 AND accepted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListWorkspaceInvitations(ctx context.Context, workspaceID string) ([]WorkspaceInvitation, error) {
	rows, err := q.db.Query(ctx, listWorkspaceInvitations, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceInvitation{}
	for rows.Next() {
		var i WorkspaceInvitation
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.TokenHash,
			&i.InvitedBy,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT
    wm.workspace_id,
    wm.user_id,
    wm.role,
    wm.invited_by,
    wm.created_at,
    wm.updated_at,
    u.name       AS user_name,
    u.email      AS user_email,
    u.avatar_url AS user_avatar_url
FROM workspace_members wm
JOIN users u ON u.id = wm.user_id
WHERE wm.workspace_id = $1
ORDER BY wm.created_at ASC
`

type ListWorkspaceMembersRow struct {
	WorkspaceID   string    `json:"workspace_id"`
	UserID        string    `json:"user_id"`
	Role          string    `json:"role"`
	InvitedBy     *string   `json:"invited_by"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
	UserName      string    `json:"user_name"`
	UserEmail     string    `json:"user_email"`
	UserAvatarUrl *string   `json:"user_avatar_url"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID string) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.UserAvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT w.id, w.name, w.slug, w.status, w.deleted_at, w.created_at, w.updated_at, wm.role
FROM workspaces w
JOIN workspace_members wm ON wm.workspace_id = w.id
WHERE wm.user_id = $1 AND w.deleted_at IS NULL
ORDER BY wm.created_at ASC
`

type ListWorkspacesByUserRow struct {
	ID        string     `json:"id"`
	Name      string     `json:"name"`
	Slug      string     `json:"slug"`
	Status    string     `json:"status"`
	DeletedAt *time.Time `json:"deleted_at"`
	CreatedAt time.Time  `json:"created_at"`
	UpdatedAt time.Time  `json:"updated_at"`
	Role      string     `json:"role"`
}

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID string) ([]ListWorkspacesByUserRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesByUserRow{}
	for rows.Next() {
		var i ListWorkspacesByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.Status,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspace = `-- name: LockWorkspace :one
SELECT 1 FROM workspaces WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockWorkspace(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, lockWorkspace, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const provisionWorkspace = `-- name: ProvisionWorkspace :exec
UPDATE workspaces
SET status = 'active', updated_at = NOW()
WHERE id = $1 AND status = 'pending' AND deleted_at IS NULL
`

// Webhook + Provision path: flip a draft workspace to active.
func (q *Queries) ProvisionWorkspace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, provisionWorkspace, id)
	return err
}

const softDeleteWorkspace = `-- name: SoftDeleteWorkspace :exec
UPDATE workspaces
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteWorkspace(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteWorkspace, id)
	return err
}

const updateWorkspaceMemberRole = `-- name: UpdateWorkspaceMemberRole :exec
UPDATE workspace_members
SET role = $3, updated_at = NOW()
WHERE workspace_id = $1 AND user_id = $2
`

type UpdateWorkspaceMemberRoleParams struct {
	WorkspaceID string `json:"workspace_id"`
	UserID      string `json:"user_id"`
	Role        string `json:"role"`
}

func (q *Queries) UpdateWorkspaceMemberRole(ctx context.Context, arg UpdateWorkspaceMemberRoleParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceMemberRole, arg.WorkspaceID, arg.UserID, arg.Role)
	return err
}

const updateWorkspaceStatus = `-- name: UpdateWorkspaceStatus :one
UPDATE workspaces
SET status = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, slug, status, deleted_at, created_at, updated_at
`

type UpdateWorkspaceStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceStatus, arg.ID, arg.Status)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.Status,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
