// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_apps.sql

package sqlc

import (
	"context"
)

const countWorkspaceAppsByWorkspace = `-- name: CountWorkspaceAppsByWorkspace :one
SELECT COUNT(*) FROM workspace_apps
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountWorkspaceAppsByWorkspace(ctx context.Context, workspaceID string) (int64, error) {
	row := q.db.QueryRow(ctx, countWorkspaceAppsByWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const findWorkspaceAppByID = `-- name: FindWorkspaceAppByID :one
SELECT id, workspace_id, created_by, name, platform, bundle_id, team_id, app_store_url, package_name, sha256_fingerprints, play_store_url, scheme, deleted_at, created_at, updated_at FROM workspace_apps
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type FindWorkspaceAppByIDParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) FindWorkspaceAppByID(ctx context.Context, arg FindWorkspaceAppByIDParams) (WorkspaceApp, error) {
	row := q.db.QueryRow(ctx, findWorkspaceAppByID, arg.ID, arg.WorkspaceID)
	var i WorkspaceApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Name,
		&i.Platform,
		&i.BundleID,
		&i.TeamID,
		&i.AppStoreUrl,
		&i.PackageName,
		&i.Sha256Fingerprints,
		&i.PlayStoreUrl,
		&i.Scheme,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspaceApp = `-- name: InsertWorkspaceApp :one
INSERT INTO workspace_apps (
    id, workspace_id, created_by, name, platform,
    bundle_id, team_id, app_store_url,
    package_name, sha256_fingerprints, play_store_url,
    scheme
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11,
    $12
) RETURNING id, workspace_id, created_by, name, platform, bundle_id, team_id, app_store_url, package_name, sha256_fingerprints, play_store_url, scheme, deleted_at, created_at, updated_at
`

type InsertWorkspaceAppParams struct {
	ID                 string   `json:"id"`
	WorkspaceID        string   `json:"workspace_id"`
	CreatedBy          *string  `json:"created_by"`
	Name               string   `json:"name"`
	Platform           string   `json:"platform"`
	BundleID           *string  `json:"bundle_id"`
	TeamID             *string  `json:"team_id"`
	AppStoreUrl        *string  `json:"app_store_url"`
	PackageName        *string  `json:"package_name"`
	Sha256Fingerprints []string `json:"sha256_fingerprints"`
	PlayStoreUrl       *string  `json:"play_store_url"`
	Scheme             *string  `json:"scheme"`
}

func (q *Queries) InsertWorkspaceApp(ctx context.Context, arg InsertWorkspaceAppParams) (WorkspaceApp, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceApp,
		arg.ID,
		arg.WorkspaceID,
		arg.CreatedBy,
		arg.Name,
		arg.Platform,
		arg.BundleID,
		arg.TeamID,
		arg.AppStoreUrl,
		arg.PackageName,
		arg.Sha256Fingerprints,
		arg.PlayStoreUrl,
		arg.Scheme,
	)
	var i WorkspaceApp
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.CreatedBy,
		&i.Name,
		&i.Platform,
		&i.BundleID,
		&i.TeamID,
		&i.AppStoreUrl,
		&i.PackageName,
		&i.Sha256Fingerprints,
		&i.PlayStoreUrl,
		&i.Scheme,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspaceAppsByPlatform = `-- name: ListWorkspaceAppsByPlatform :many
SELECT id, workspace_id, created_by, name, platform, bundle_id, team_id, app_store_url, package_name, sha256_fingerprints, play_store_url, scheme, deleted_at, created_at, updated_at FROM workspace_apps
WHERE workspace_id = $1 AND platform = $2 AND deleted_at IS NULL
ORDER BY name
`

type ListWorkspaceAppsByPlatformParams struct {
	WorkspaceID string `json:"workspace_id"`
	Platform    string `json:"platform"`
}

// "platform" here means the target OS ("ios" or "android"), not platform apps.
// Used by AASA/assetlinks to fetch only the relevant OS's apps for a domain.
func (q *Queries) ListWorkspaceAppsByPlatform(ctx context.Context, arg ListWorkspaceAppsByPlatformParams) ([]WorkspaceApp, error) {
	rows, err := q.db.Query(ctx, listWorkspaceAppsByPlatform, arg.WorkspaceID, arg.Platform)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceApp{}
	for rows.Next() {
		var i WorkspaceApp
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.Name,
			&i.Platform,
			&i.BundleID,
			&i.TeamID,
			&i.AppStoreUrl,
			&i.PackageName,
			&i.Sha256Fingerprints,
			&i.PlayStoreUrl,
			&i.Scheme,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceAppsByWorkspace = `-- name: ListWorkspaceAppsByWorkspace :many
SELECT id, workspace_id, created_by, name, platform, bundle_id, team_id, app_store_url, package_name, sha256_fingerprints, play_store_url, scheme, deleted_at, created_at, updated_at FROM workspace_apps
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListWorkspaceAppsByWorkspace(ctx context.Context, workspaceID string) ([]WorkspaceApp, error) {
	rows, err := q.db.Query(ctx, listWorkspaceAppsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceApp{}
	for rows.Next() {
		var i WorkspaceApp
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.CreatedBy,
			&i.Name,
			&i.Platform,
			&i.BundleID,
			&i.TeamID,
			&i.AppStoreUrl,
			&i.PackageName,
			&i.Sha256Fingerprints,
			&i.PlayStoreUrl,
			&i.Scheme,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWorkspaceApp = `-- name: SoftDeleteWorkspaceApp :execrows
UPDATE workspace_apps SET
    deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1 AND workspace_id = $2 AND deleted_at IS NULL
`

type SoftDeleteWorkspaceAppParams struct {
	ID          string `json:"id"`
	WorkspaceID string `json:"workspace_id"`
}

func (q *Queries) SoftDeleteWorkspaceApp(ctx context.Context, arg SoftDeleteWorkspaceAppParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteWorkspaceApp, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
