[build]
  cmd = "go build -o ./tmp/api ./cmd/api"
  entrypoint = ["./tmp/api"]
  include_ext = ["go", "toml", "yaml"]
  exclude_dir = ["tmp", "bin", "vendor", "sql"]
  exclude_regex = ["_test\\.go"]
  exclude_unchanged = true
  stop_on_error = true
  delay = 1000
  kill_delay = 3000000000  # 3s in nanoseconds
  send_interrupt = true
  log = "build-errors.log"

[misc]
  clean_on_exit = true

[screen]
  clear_on_rebuild = true
  keep_scroll = true
